# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a100tcsg324-1Q
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  E:/DSPIC_final/DSPIC_final.srcs/sources_1/new/sub.v
  E:/DSPIC_final/DSPIC_final.srcs/sources_1/new/add.v
  E:/DSPIC_final/DSPIC_final.srcs/sources_1/new/flp32_add_sub.v
  E:/DSPIC_final/DSPIC_final.srcs/sources_1/new/flp32_complex_subtracter.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/DSPIC_final/DSPIC_final.data/wt [current_project]
set_property parent.project_dir E:/DSPIC_final [current_project]
synth_design -top flp32_complex_subtracter -part xa7a100tcsg324-1Q
write_checkpoint flp32_complex_subtracter.dcp
report_utilization -file flp32_complex_subtracter_utilization_synth.rpt -pb flp32_complex_subtracter_utilization_synth.pb
