# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7a100tcsg324-2I
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {{E:/Leo/DSP hw2/prob1/prob1.srcs/sources_1/new/mult_10bits.v}}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Leo/DSP hw2/prob1/prob1.data/wt} [current_project]
set_property parent.project_dir {E:/Leo/DSP hw2/prob1} [current_project]
synth_design -top mult_10bits -part xa7a100tcsg324-2I
write_checkpoint mult_10bits.dcp
report_utilization -file mult_10bits_utilization_synth.rpt -pb mult_10bits_utilization_synth.pb
